const MINIMAL_SYMBOLS = 3;
const MINIMAL_SYMBOLS_ERROR = 'Не менее трех символов';
const INCORRECT_EMAIL_ERROR = 'Некорректный формат почты';

const TABLET_WIDTH = 600;
const DESK_WIDTH = 938;
const FULLSCREEN_WIDTH = 1234;

const MOVIES_SHOWN_MOBILE = 5;
const MOVIES_SHOWN_TABLET = 8;
const MOVIES_SHOWN_DESK = 9;
const MOVIES_SHOWN_FULLSCREEN = 12;

const MOVIES_MORE_MOBILE = 1;
const MOVIES_MORE_TABLET = 2;
const MOVIES_MORE_DESK = 3;
const MOVIES_MORE_FULLSCREEN = 4;

const SHORT_MOVIE_DURATION = 40;

export {
  MINIMAL_SYMBOLS,
  MINIMAL_SYMBOLS_ERROR,
  INCORRECT_EMAIL_ERROR,
  MOVIES_SHOWN_MOBILE,
  MOVIES_SHOWN_TABLET,
  MOVIES_SHOWN_DESK,
  MOVIES_SHOWN_FULLSCREEN,
  TABLET_WIDTH,
  DESK_WIDTH,
  FULLSCREEN_WIDTH,
  MOVIES_MORE_MOBILE,
  MOVIES_MORE_TABLET,
  MOVIES_MORE_DESK,
  MOVIES_MORE_FULLSCREEN,
  SHORT_MOVIE_DURATION,
};
